(async()=>{
const $=s=>document.querySelector(s);
let D=YQ_DEFAULT,API=false;
try{const r=await fetch('api/data',{cache:'no-store'});if(r.ok){const j=await r.json();API=true;if(j&&j.days)D={...YQ_DEFAULT,...j}}}catch(e){}
if(!API){try{const l=JSON.parse(localStorage.getItem('yq-data'));if(l)D={...YQ_DEFAULT,...l}}catch(e){}}
const pg=document.body.dataset.page,O=D.ov||{},ov=k=>O[k]!==undefined&&O[k]!==null&&O[k]!=='';
const num=v=>parseFloat(String(v).replace(/[$,%\s]/g,''))||0;
const esc=t=>String(t==null?'':t).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const sum=(a,f)=>a.reduce((s,x)=>s+(+f(x)||0),0);
const comp=a=>(a.reduce((c,v)=>c*(1+v/100),1)-1)*100;
const $m=n=>(n<0?'-':'')+'$'+Math.abs(Math.round(n)).toLocaleString('en-US');
const $p=n=>'$'+(+n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const fu=u=>u&&u.length>10?new Date(u).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):fd(u);
const pct=v=>`<span class="${v<0?'neg':'pos'}">${v>=0?'+':''}${v.toFixed(2)}%</span>`;
const gn=v=>`<span class="${v<0?'neg':'pos'}">${v<0?'-':'+'}$${Math.abs(Math.round(v)).toLocaleString('en-US')}</span>`;
const dt=d=>new Date(d+'T00:00:00');
const fd=d=>d?dt(d).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'';
const wd=d=>dt(d).toLocaleDateString('en-US',{weekday:'short'});
const days=[...D.days].sort((a,b)=>a.d<b.d?-1:a.d>b.d?1:0),allH=D.holdings,isC=h=>+h.proc>0&&!+h.shares,hold=allH.filter(h=>!isC(h));
const L=days.length?days[days.length-1]:{d:'',p:0,g:0},T0=L.d?dt(L.d).getTime():0;
const per=f=>{const a=days.filter(f);return{p:comp(a.map(x=>x.p)),g:sum(a,x=>x.g)}};
const P={'Today':per(x=>x.d==L.d),'7 days':per(x=>dt(x.d).getTime()>=T0-6*864e5),'Month to date':per(x=>x.d.slice(0,7)==L.d.slice(0,7)),'Year to date':per(x=>x.d.slice(0,4)==L.d.slice(0,4)),'Since inception':per(()=>true)};if(ov('mtd'))P['Month to date'].p=num(O.mtd);if(ov('mtdg'))P['Month to date'].g=num(O.mtdg);if(ov('ytd'))P['Year to date'].p=num(O.ytd);if(ov('ytdg'))P['Year to date'].g=num(O.ytdg);
const grp=n=>{const o=[];days.forEach(x=>{const k=x.d.slice(0,n);let m=o[o.length-1];if(!m||m.k!=k){m={k,a:[],g:0};o.push(m)}m.a.push(x.p);m.g+=+x.g||0});o.forEach(m=>m.p=comp(m.a));return o};const months=grp(7),years=grp(4);
const mn=k=>new Date(k+'-01T00:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'});
const totVal=sum(hold,h=>h.val),totInv=ov('inv')?num(O.inv):sum(hold,h=>h.inv),dVal=ov('val')?num(O.val):totVal,tg=ov('gain')?num(O.gain):totVal-totInv,tgp=ov('gainp')?num(O.gainp):totInv?tg/totInv*100:0;
const kpi=(l,v,s)=>`<div class="kpi"><small>${l}</small><strong>${v}</strong>${s?`<em>${s}</em>`:''}</div>`;
const head=(t,s)=>`<div class="ph"><h1>${t}</h1><p class="lead">${s}</p><p class="stamp">Last updated ${fu(D.updated)}${D.start?' · Running since '+fd(D.start):''}</p></div>`;
function line(h,ds,val){ds=ds||days;let c=100,v=[100];ds.forEach(x=>{c*=1+x.p/100;v.push(c)});if(val&&totVal){const e=v[v.length-1];v=v.map(a=>a/e*totVal)}
 const W=640,L0=46,B=26,mx=Math.max(...v),lo0=Math.min(...v),pd=(mx-lo0||1)*.1,hi=mx+pd,lo=lo0-pd,X=i=>L0+i/(v.length-1||1)*(W-L0-8),Y=a=>8+(hi-a)/(hi-lo)*(h-B-8);
 const grid=[0,1,2,3].map(i=>{const a=lo+(hi-lo)*i/3,y=Y(a);return `<line x1="${L0}" x2="${W}" y1="${y}" y2="${y}" stroke="#e3e7ee"/><text x="${L0-8}" y="${y+4}" text-anchor="end">${val?(a>=1e6?(a/1e6).toFixed(2)+'M':(a/1e3).toFixed(0)+'k'):a.toFixed(0)}</text>`}).join('');
 const pts=v.map((a,i)=>X(i).toFixed(1)+','+Y(a).toFixed(1)).join(' ');
 return `<svg viewBox="0 0 ${W} ${h}" class="ch">${grid}<polygon points="${L0},${h-B} ${pts} ${W-8},${h-B}" fill="#1f5fa8" opacity=".08"/><polyline class="draw" pathLength="1000" points="${pts}" fill="none" stroke="#1f5fa8" stroke-width="2" stroke-linejoin="round"/><text x="${L0}" y="${h-6}">${fd(ds.length?ds[0].d:'')}</text><text x="${W-8}" y="${h-6}" text-anchor="end">${fd(ds.length?ds[ds.length-1].d:'')}</text></svg>`}
function bars(a,lab){const m=Math.max(...a.map(x=>Math.abs(x.p)),.1),W=640,H=200,z=96,w=(W-46)/(a.length||1);
 return `<svg viewBox="0 0 ${W} ${H}" class="ch"><line x1="40" x2="${W}" y1="${z}" y2="${z}" stroke="#c9d0db"/><text x="34" y="${z+4}" text-anchor="end">0%</text><text x="34" y="14" text-anchor="end">${m.toFixed(1)}%</text><text x="34" y="${H-30}" text-anchor="end">-${m.toFixed(1)}%</text>${a.map((x,i)=>{const hh=Math.abs(x.p)/m*80;return `<rect x="${44+i*w+w*.15}" y="${x.p>=0?z-hh:z}" width="${w*.7}" height="${Math.max(hh,1)}" rx="1.5" fill="${x.p>=0?'#0a7d4f':'#c0392b'}"><title>${x.t}: ${x.p.toFixed(2)}%</title></rect>`+(lab?`<text x="${44+i*w+w/2}" y="${H-6}" text-anchor="middle">${x.l}</text>`:'')}).join('')}${!lab&&a.length?`<text x="44" y="${H-6}">${a[0].t}</text><text x="${W}" y="${H-6}" text-anchor="end">${a[a.length-1].t}</text>`:''}</svg>`}
const mv=x=>{const e=Object.entries(x.h||{}).sort((a,b)=>b[1]-a[1]);const m=e.length?`${esc(e[0][0])} ${e[0][1]>=0?'+':''}${e[0][1]}%`+(e.length>1?` · ${esc(e[e.length-1][0])} ${e[e.length-1][1]}%`:''):'';return esc(x.n||'')+(x.n&&m?'<br>':'')+(m?`<small>${m}</small>`:'')};
const dtable=n=>`<div class="tw"><table><tr><th>Date</th><th class="r">Daily gain</th><th class="r">Daily gain ($)</th><th>Notes and movers</th></tr>${days.slice().reverse().slice(0,n||99999).map((x,i)=>`<tr class="${!n&&i>=30?'x':''}"><td>${wd(x.d)}, ${fd(x.d)}</td><td class="r">${pct(x.p)}</td><td class="r">${gn(x.g)}</td><td>${mv(x)}</td></tr>`).join('')}</table></div>`;
const ps=days.map(x=>x.p),mean=ps.length?sum(ps,x=>x)/ps.length:0,sd=ps.length>1?Math.sqrt(sum(ps,x=>(x-mean)**2)/(ps.length-1)):0;
let pk=1,cu=1,mdd=0;days.forEach(x=>{cu*=1+x.p/100;pk=Math.max(pk,cu);mdd=Math.min(mdd,(cu/pk-1)*100)});
const best=days.reduce((a,x)=>!a||x.p>a.p?x:a,null)||{p:0,d:''},worst=days.reduce((a,x)=>!a||x.p<a.p?x:a,null)||{p:0,d:''};
const bmo=months.reduce((a,m)=>!a||m.p>a.p?m:a,null),wmo=months.reduce((a,m)=>!a||m.p<a.p?m:a,null);let stk=0;if(days.length){const up=L.p>=0;for(let i=days.length-1;i>=0&&(days[i].p>=0)==up;i--)stk++}
const statCards=()=>[bmo?kpi('Best month',pct(bmo.p),mn(bmo.k)):'',wmo?kpi('Worst month',pct(wmo.p),mn(wmo.k)):'',kpi('Current streak',stk+(stk==1?' day':' days'),days.length?(L.p>=0?'up days':'down days'):''),kpi('Best day',pct(best.p),fd(best.d)),kpi('Worst day',pct(worst.p),fd(worst.d)),kpi('Days up',(ps.length?ps.filter(x=>x>0).length/ps.length*100:0).toFixed(0)+'%',ps.length+' days logged'),kpi('Average day',pct(mean)),kpi('Volatility (annualized)',(sd*Math.sqrt(252)).toFixed(1)+'%'),kpi('Max drawdown',pct(mdd),'peak to trough')].join('');
const B=D.bench||{name:'Benchmark',months:[]},bm={};B.months.forEach(x=>bm[x.k]=+x.p);
const bcard=()=>{const r=months.filter(m=>m.k in bm);if(!r.length)return'';const yp=comp(r.map(m=>m.p)),bp=comp(r.map(m=>bm[m.k]));
 return `<div class="card"><h3>Versus ${esc(B.name)}</h3><div class="kpis">${kpi(esc(D.firm),pct(yp),'months compared')}${kpi(esc(B.name),pct(bp))}${kpi('Difference',pct(yp-bp))}</div><div class="tw"><table><tr><th>Month</th><th class="r">Portfolio</th><th class="r">${esc(B.name)}</th><th class="r">Difference</th></tr>${r.slice().reverse().map(m=>`<tr><td>${mn(m.k)}</td><td class="r">${pct(m.p)}</td><td class="r">${pct(bm[m.k])}</td><td class="r">${pct(m.p-bm[m.k])}</td></tr>`).join('')}</table></div></div>`};
const calcCard=()=>`<div class="card"><h3>What would it be worth?</h3><div class="row3"><div><label>Amount ($)</label><input id="ca" type="number" value="10000"></div><div><label>Period</label><select id="cp">${Object.keys(P).slice(1).reverse().map(k=>`<option>${k}</option>`).join('')}</select></div><div><label>Result</label><div class="big" style="font-size:30px;margin:0" id="cr"></div></div></div><p class="note">Based on the returns logged on this site. For illustration only. Past performance does not guarantee future results.</p></div>`;
const faqCard=()=>(D.faq||[]).length?`<div class="card"><h3>Frequently asked questions</h3>${D.faq.map(f=>`<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</div>`:'';
const pview=v=>{const f={day:[days.slice(-30).map(x=>({p:x.p,t:fd(x.d)})),0,'Day',days.slice().reverse().slice(0,90).map(x=>[wd(x.d)+', '+fd(x.d),x.p,x.g])],month:[months.slice(-12).map(m=>({p:m.p,t:mn(m.k),l:mn(m.k).split(' ')[0]})),1,'Month',months.slice().reverse().map(m=>[mn(m.k),m.p,m.g])],year:[years.map(y=>({p:y.p,t:y.k,l:y.k})),1,'Year',years.slice().reverse().map(y=>[y.k,y.p,y.g])]}[v];
 return bars(f[0],f[1])+`<div class="tw"><table><tr><th>${f[2]}</th><th class="r">Profit (%)</th><th class="r">Profit ($)</th></tr>${f[3].map(r=>`<tr><td>${r[0]}</td><td class="r">${pct(r[1])}</td><td class="r">${gn(r[2])}</td></tr>`).join('')}</table></div>`};
const pages=[['index','Home'],['daily','Daily gains'],['performance','Profits'],['portfolio','Portfolio'],['trades','Trades'],['updates','Updates'],['why-invest','Why invest'],['invest','Invest']];
const file={home:'index',daily:'daily',performance:'performance',portfolio:'portfolio',trades:'trades',updates:'updates',why:'why-invest',invest:'invest'}[pg];
const shell=c=>`<header><div class="wrap"><a class="logo" href="index.html"><span class="mark">${esc((D.firm||'Y')[0])}</span>${esc(D.firm)}</a><nav>${pages.map(p=>`<a href="${p[0]}.html" class="${p[0]==file?'on':''} ${p[0]=='invest'?'cta':''}">${p[1]}</a>`).join('')}</nav></div></header><main><div class="wrap">${c}</div></main><footer><div class="wrap">Last updated ${fu(D.updated)}. Past performance does not guarantee future results. Investing involves risk, including loss of principal. This site is informational and is not an offer or financial advice. <a href="#" onclick="window.print();return false" style="opacity:.6">Print</a> · <a href="admin.html" style="opacity:.6">Admin</a> · v6</div></footer>`;
const cols=['#12263f','#1f5fa8','#3f8fd2','#0b7a6e','#5bb3a6','#9aa9bd','#c3a24a','#d5dbe4'];
const R={};
R.home=()=>`<section class="hero"><div><h1>${esc(D.headline)}</h1><p class="lead">${esc(D.sub)}</p><div class="btns"><a class="btn pri" href="daily.html">See daily gains</a><a class="btn" href="portfolio.html">View portfolio</a><a class="btn" href="invest.html">Invest</a></div></div>
<div class="card" style="margin:0"><small>Portfolio value</small><strong class="big">${$m(dVal)}</strong><div>${gn(L.g)} &nbsp;${pct(L.p)} <small>on ${fd(L.d)}</small></div><p class="stamp">Last updated ${fu(D.updated)}</p><div style="margin-top:12px">${line(170)}</div></div></section>
<div class="kpis">${kpi('Total invested',$m(totInv))}${kpi('Total gain',gn(tg),pct(tgp)+' on invested')}${kpi('Month to date',pct(P['Month to date'].p),gn(P['Month to date'].g))}${kpi('Year to date',pct(P['Year to date'].p),gn(P['Year to date'].g))}${kpi('Investors',D.investors,'Since '+(D.start?fd(D.start):D.since))}</div>
${(D.updates||[]).length?`<section class="card"><h3>Latest updates</h3>${D.updates.slice().sort((a,b)=>a.d<b.d?1:-1).slice(0,3).map(u=>`<div class="upd"><small>${fd(u.d)}</small><b>${esc(u.t)}</b><p>${esc(u.b)}</p></div>`).join('')}</section>`:''}<section class="card"><div class="head"><h3>Latest daily gains</h3><a href="daily.html">All daily gains</a></div>${dtable(5)}</section>`;
R.daily=()=>`${head('Daily gains','Every trading day, as logged.')}<div class="kpis">${kpi('Latest day',pct(L.p),fd(L.d))}${kpi('Latest gain',gn(L.g))}${kpi('Last 7 days',pct(P['7 days'].p),gn(P['7 days'].g))}${kpi('Month to date',pct(P['Month to date'].p),gn(P['Month to date'].g))}</div>
<div class="card"><h3>Last 30 days</h3>${bars(days.slice(-30).map(x=>({p:x.p,t:fd(x.d)})))}</div>${monthCard()}
<div class="card"><div class="head"><h3>Daily log</h3><div class="btns"><button class="btn sm" id="csvx">Download CSV</button><button class="btn sm" id="more">Show all</button></div></div><div id="dt">${dtable()}</div></div>`;
R.performance=()=>`${head('Profits','See profit by day, month or year.')}<div class="kpis">${Object.keys(P).map(k=>kpi(k,pct(P[k].p),gn(P[k].g))).join('')}</div>
<div class="card"><div class="head"><h3>Profit by period</h3><div class="seg" id="seg"><button data-v="day">Day</button><button data-v="month">Month</button><button data-v="year">Year</button></div></div><div id="pv"></div></div>
${bcard()}<div class="card"><h3>Risk and consistency</h3><div class="kpis" style="margin:0">${statCards()}</div></div><div class="card"><h3>Growth of 100 since the first logged day</h3>${line(260)}</div>${valCard()}`;
R.invest=()=>`${head('Invest with Yaktonian Equity','Tell us a little about you and we will get in touch with the next steps.')}<div class="split2"><div class="card"><h3>Contact us</h3><form id="cf"><div class="row3"><div><label>Full name</label><input name="name" required></div><div><label>Email</label><input name="email" type="email" required></div><div><label>Phone (optional)</label><input name="phone"></div></div><label>Amount you are considering</label><input name="amount" placeholder="e.g. $10,000"><label>Message</label><textarea name="message" placeholder="Questions, timing, anything we should know"></textarea><div class="btns" style="margin-top:16px"><button class="btn pri" type="submit">Send enquiry</button></div><p class="note" id="cm"></p></form></div>
<div><div class="card"><h3>How it works</h3><ol class="steps"><li><b>Get in touch.</b> Send an enquiry and we will reply with details.</li><li><b>Review the terms.</b> We go through the strategy, fees and risks with you.</li><li><b>Decide.</b> Invest only once you are comfortable with the terms.</li></ol></div><div class="card"><h3>Details</h3><div class="tw"><table style="min-width:0"><tr><td>Minimum investment</td><td class="r">${D.minInvest}</td></tr><tr><td>Email</td><td class="r"><a href="mailto:${D.contactEmail}" style="color:var(--blue)">${D.contactEmail}</a></td></tr><tr><td>Phone</td><td class="r">${D.phone}</td></tr></table></div></div></div></div>${calcCard()}${faqCard()}`;
R.portfolio=()=>{let a=0;const g=hold.map((h,i)=>{const s=a;a+=totVal?h.val/totVal*100:0;return `${cols[i%8]} ${s}% ${a}%`}).join(',');
 const cls={};hold.forEach(h=>{const c=cls[h.c]=cls[h.c]||{inv:0,val:0};c.inv+=+h.inv||0;c.val+=+h.val||0});
 const row=(h,i)=>{const sh=+h.shares||0,avg=sh?h.inv/sh:0,px=sh?h.val/sh:0;return `<tr><td><span class="dot" style="background:${cols[i%8]}"></span><b>${esc(h.n)}</b><br><small>${esc(h.t)}, ${esc(h.c)}</small>${+h.proc>0?'<br><small>Partly sold, last '+(fd(h.sold)||'')+'</small>':''}</td><td>${h.date?fd(h.date):'—'}</td><td class="r">${sh?sh.toLocaleString('en-US'):'—'}</td><td class="r">${sh?$p(avg):'—'}</td><td class="r">${sh?$p(px):'—'}</td><td class="r">${$m(h.inv)}</td><td class="r">${$m(h.val)}</td><td class="r">${gn(h.val-h.inv)}</td><td class="r">${pct(h.inv?(h.val/h.inv-1)*100:0)}</td><td class="r">${totVal?(h.val/totVal*100).toFixed(1):0}%</td></tr>`};
 return `${head('Portfolio','How much we have invested, when, and where it sits today.')}<div class="kpis">${kpi('Total invested',$m(totInv))}${kpi('Current value',$m(dVal))}${kpi('Total gain',gn(tg))}${kpi('Return on invested',pct(tgp))}${hk()}</div>
${valCard()}<div class="split"><div class="card"><h3>Allocation</h3><div class="donut" style="background:conic-gradient(${g})"></div></div><div class="card"><h3>By asset class</h3><div class="tw"><table><tr><th>Class</th><th class="r">Invested</th><th class="r">Value</th><th class="r">Weight</th></tr>${Object.keys(cls).map(k=>`<tr><td>${esc(k)}</td><td class="r">${$m(cls[k].inv)}</td><td class="r">${$m(cls[k].val)}</td><td class="r">${totVal?(cls[k].val/totVal*100).toFixed(1):0}%</td></tr>`).join('')}</table></div></div></div>
<div class="card"><div class="head"><h3>Holdings</h3><button class="btn sm" id="hcsv">Download CSV</button></div><div class="tw"><table><tr><th>Holding</th><th>First invested</th><th class="r">Shares</th><th class="r">Avg cost</th><th class="r">Price</th><th class="r">Invested</th><th class="r">Value</th><th class="r">Gain / loss</th><th class="r">Return</th><th class="r">Weight</th></tr>${hold.map(row).join('')}<tr class="tot"><td>Total</td><td></td><td></td><td></td><td></td><td class="r">${$m(totInv)}</td><td class="r">${$m(totVal)}</td><td class="r">${gn(tg)}</td><td class="r">${pct(tgp)}</td><td class="r">100%</td></tr></table></div><p class="note">Price is current value divided by shares owned. Average cost is the amount invested divided by shares.</p></div>${closedCard()}`};
const monthCard=()=>months.length?`<div class="card"><div class="head"><h3>Browse a past month</h3><select id="mp" style="width:auto">${months.slice().reverse().map(m=>`<option value="${m.k}">${mn(m.k)}</option>`).join('')}</select></div><div id="mpv"></div></div>`:'';
const valCard=()=>days.length?`<div class="card"><div class="head"><h3>Portfolio value over time</h3><div class="seg" id="rg"><button data-r="21">1M</button><button data-r="63">3M</button><button data-r="252">1Y</button><button data-r="0">All</button></div></div><div id="rgv"></div><p class="note">Worked back from today's value using the daily returns.</p></div>`:'';
const topH=f=>hold.reduce((a,h)=>f(h)>f(a)?h:a,hold[0]),hk=()=>{if(!hold.length)return'';const a=topH(h=>h.val),b=topH(h=>h.inv?h.val/h.inv:-9);return kpi('Largest holding',esc(a.t||a.n),(totVal?a.val/totVal*100:0).toFixed(1)+'% of portfolio')+kpi('Best performer',esc(b.t||b.n),pct(b.inv?(b.val/b.inv-1)*100:0))};
const closedCard=()=>{const a=allH.filter(h=>+h.proc>0);if(!a.length)return'';return `<div class="card"><h3>Sold positions</h3><div class="tw"><table><tr><th>Holding</th><th>Status</th><th>First bought</th><th>Last sold</th><th class="r">Cost of shares sold</th><th class="r">Proceeds</th><th class="r">Realized gain</th></tr>${a.map(h=>`<tr><td><b>${esc(h.n)}</b><br><small>${esc(h.t)}</small></td><td>${isC(h)?'Fully sold':'Partly sold'}</td><td>${fd(h.date)||'—'}</td><td>${fd(h.sold)||'—'}</td><td class="r">${$m(h.sc)}</td><td class="r">${$m(h.proc)}</td><td class="r">${gn(h.proc-h.sc)}</td></tr>`).join('')}</table></div></div>`};
const side=x=>`<span class="b ${x=='SELL'?'sell':'buy'}">${esc(x)}</span>`;
R.trades=()=>{const ords=D.orders||[],trds=(D.trades||[]).slice().sort((a,b)=>a.d<b.d?1:a.d>b.d?-1:0),open=ords.filter(o=>o.status=='Open'),last=trds[0];
 const orow=o=>`<tr><td>${fd(o.d)}</td><td><b>${esc(o.t)}</b></td><td>${side(o.side)}</td><td>${esc(o.type)}</td><td class="r">${(+o.sh||0).toLocaleString('en-US')}</td><td class="r">${+o.px?$p(o.px):'Market'}</td><td class="r">${+o.px?$m(o.sh*o.px):'—'}</td><td><span class="b st ${esc(o.status)}">${esc(o.status)}</span></td></tr>`;
 return `${head('Trades','Our open buy and sell orders, and every trade we have made.')}<div class="kpis">${kpi('Open orders',open.length,'waiting to execute')}${kpi('Trades logged',trds.length)}${kpi('Realized profit',gn(sum(allH,h=>(+h.proc||0)-(+h.sc||0))),'from sold shares')}${kpi('Last trade',last?side(last.side)+' '+esc(last.t):'None',last?fd(last.d):'')}</div>
<div class="card"><h3>Orders</h3>${ords.length?`<div class="tw"><table><tr><th>Placed</th><th>Holding</th><th>Side</th><th>Type</th><th class="r">Shares</th><th class="r">Price</th><th class="r">Est. value</th><th>Status</th></tr>${ords.slice().sort((a,b)=>(a.status=='Open'?0:1)-(b.status=='Open'?0:1)||(a.d<b.d?1:-1)).map(orow).join('')}</table></div>`:'<p class="note">No orders right now.</p>'}</div>
<div class="card"><div class="head"><h3>Trade history</h3><button class="btn sm" id="tcsv">Download CSV</button></div>${trds.length?`<div class="tw"><table><tr><th>Date</th><th>Holding</th><th>Side</th><th class="r">Shares</th><th class="r">Price</th><th class="r">Total</th><th class="r">Realized</th><th>Note</th></tr>${trds.map(x=>`<tr><td>${fd(x.d)}</td><td><b>${esc(x.t)}</b></td><td>${side(x.side)}</td><td class="r">${(+x.sh||0).toLocaleString('en-US')}</td><td class="r">${$p(x.px)}</td><td class="r">${$m(x.sh*x.px)}</td><td class="r">${x.pl!=null?gn(x.pl):'—'}</td><td>${esc(x.note)}</td></tr>`).join('')}</table></div>`:'<p class="note">No trades logged yet.</p>'}</div>`};
R.updates=()=>`${head('Updates','News from the team. Anyone can like. Create an account to reply.')}<div id="fd"></div>`;
R.why=()=>`${head('Why invest','Five principles behind how Yaktonian Equity is run.')}<div class="grid">${[['Diversified by design','Capital is spread across equities, funds, bonds, commodities and cash, so no single position decides the outcome.'],['Transparent numbers','Every daily gain and every holding is published on this site, with what was invested and what it is worth now.'],['Patience over prediction','We aim to compound steadily and avoid chasing short-term moves.'],['Risk is managed first','Position sizes are capped and a cash reserve is always held.'],['Aligned incentives','Our own capital sits in the same portfolio as yours.']].map(x=>`<div class="card"><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div><div class="btns sec"><a class="btn pri" href="performance.html">See the track record</a><a class="btn" href="portfolio.html">See the holdings</a></div>`;
R.admin=()=>`${head('Admin panel','Update returns, holdings and site details.')}<div id="adm"></div>`;
$('#app').innerHTML=shell(R[pg]());
if($('#rg')){const sr=n=>{$('#rgv').innerHTML=line(240,n?days.slice(-n):days,1);document.querySelectorAll('#rg button').forEach(b=>b.classList.toggle('on',+b.dataset.r==n))};$('#rg').addEventListener('click',e=>{if(e.target.dataset.r!==undefined)sr(+e.target.dataset.r)});sr(0)}
if($('#mp')){const sm=k=>{const a=days.filter(x=>x.d.slice(0,7)==k),b=a.reduce((m,x)=>!m||x.p>m.p?x:m,null),w=a.reduce((m,x)=>!m||x.p<m.p?x:m,null);$('#mpv').innerHTML=`<div class="kpis">${kpi('Month return',pct(comp(a.map(x=>x.p))),a.length+' days')}${kpi('Month gain',gn(sum(a,x=>x.g)))}${b?kpi('Best day',pct(b.p),fd(b.d)):''}${w?kpi('Worst day',pct(w.p),fd(w.d)):''}</div>`+bars(a.map(x=>({p:x.p,t:fd(x.d)})))+line(200,a,0)};$('#mp').onchange=e=>sm(e.target.value);sm($('#mp').value)}
if($('#seg')){const sh=v=>{$('#pv').innerHTML=pview(v);document.querySelectorAll('#seg button').forEach(b=>b.classList.toggle('on',b.dataset.v==v))};$('#seg').addEventListener('click',e=>{if(e.target.dataset.v)sh(e.target.dataset.v)});sh('month')}
if($('#cf'))$('#cf').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),m=$('#cm');
 if(D.formEndpoint){try{const r=await fetch(D.formEndpoint,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(f)});if(!r.ok)throw 0;e.target.reset();m.innerHTML='<span class="pos">Thanks. We have your enquiry and will be in touch.</span>'}catch(x){m.innerHTML='<span class="neg">Could not send. Please email us directly.</span>'}return}
 location.href='mailto:'+D.contactEmail+'?subject='+encodeURIComponent('Investment enquiry from '+f.name)+'&body='+encodeURIComponent(`Name: ${f.name}\nEmail: ${f.email}\nPhone: ${f.phone}\nAmount: ${f.amount}\n\n${f.message}`);m.textContent='Your email app should open with the message ready to send.'};
const dlc=(n,r)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([r.map(x=>x.map(c=>'"'+String(c==null?'':c).replace(/"/g,'""')+'"').join(',')).join('\n')],{type:'text/csv'}));a.download=n;a.click()};
if($('#hcsv'))$('#hcsv').onclick=()=>dlc('holdings.csv',[['name','ticker','class','first_invested','shares','invested','value','last_sold','sale_proceeds','cost_sold']].concat(allH.map(h=>[h.n,h.t,h.c,h.date||'',h.shares||0,h.inv,h.val,h.sold||'',h.proc||0,h.sc||0])));
if($('#tcsv'))$('#tcsv').onclick=()=>dlc('trades.csv',[['date','ticker','side','shares','price','realized_pl','note']].concat((D.trades||[]).slice().sort((a,b)=>a.d<b.d?1:-1).map(x=>[x.d,x.t,x.side,x.sh,x.px,x.pl==null?'':x.pl,x.note||''])));
if($('#csvx'))$('#csvx').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['date,return_pct,gain_usd\n'+days.map(x=>`${x.d},${x.p},${x.g}`).join('\n')],{type:'text/csv'}));a.download='daily-returns.csv';a.click()};
if($('#ca')){const cc=()=>{const a=num($('#ca').value),r=(P[$('#cp').value]||P['Since inception']).p;$('#cr').innerHTML=$m(a*(1+r/100))+' '+pct(r)};$('#ca').oninput=cc;$('#cp').onchange=cc;cc()}
if($('#more'))$('#more').onclick=e=>{const o=$('#dt').classList.toggle('all');e.target.textContent=o?'Show recent':'Show all'};
async function feed(){const root=$('#fd'),anon=localStorage.getItem('yq-anon')||(()=>{const v=(crypto.randomUUID?crypto.randomUUID():String(Math.random()).slice(2)+Date.now());localStorage.setItem('yq-anon',v);return v})(),isA=!!sessionStorage.getItem('yq-pw');
 const H=()=>({'content-type':'application/json','x-token':localStorage.getItem('yq-tok')||'','x-anon':anon,'x-admin-password':sessionStorage.getItem('yq-pw')||''});
 const call=async o=>{try{const r=await fetch('api/feed',{method:'POST',headers:H(),body:JSON.stringify(o)});return{ok:r.ok,j:await r.json().catch(()=>({}))}}catch(e){return{ok:false,j:{error:'Could not reach the server.'}}}};
 let ps=[],me='',err='',op={};
 const heart=(y,n,id,rid)=>`<button class="btn sm ${y?'pri':''}" data-a="lk" data-id="${id}" ${rid?`data-rid="${rid}"`:''}>${y?'♥':'♡'} ${n}</button>`;
 const draw=()=>{root.innerHTML=`<div class="card">${me?`<b>@${esc(me)}</b> <button class="btn sm" data-a="out">Log out</button>`:`<h3>Join the conversation</h3><p class="note">Anyone can like. Create an account to reply.</p><div class="row3"><div><label>Username</label><input id="au" autocomplete="username"></div><div><label>Password (6+ characters)</label><input id="ap" type="password" autocomplete="current-password"></div><div class="btns" style="align-items:end"><button class="btn pri" data-a="in">Log in</button><button class="btn" data-a="up">Create account</button></div></div>`}<p class="note neg">${esc(err)}</p></div>${isA?`<div class="card"><h3>New update (admin)</h3><label>Title (optional)</label><input id="pt"><label>Message</label><textarea id="pb" style="font:inherit;min-height:90px"></textarea><div class="btns" style="margin-top:12px"><button class="btn pri" data-a="post">Post update</button></div></div>`:''}${ps.length?ps.map(p=>`<div class="card"><small>${fu(p.d)}</small>${p.t?`<h3 style="margin:4px 0">${esc(p.t)}</h3>`:''}<p style="white-space:pre-wrap">${esc(p.b)}</p><div class="btns" style="margin-top:12px">${heart(p.y,p.n,p.id)}<button class="btn sm" data-a="rp" data-id="${p.id}">Reply (${p.r.length})</button>${isA?`<button class="btn sm" data-a="del" data-id="${p.id}">Delete</button>`:''}</div>${p.r.map(x=>`<div class="upd"><small>@${esc(x.u)} · ${fu(x.d)}</small><p style="white-space:pre-wrap;color:var(--ink)">${esc(x.b)}</p><div class="btns">${heart(x.y,x.n,p.id,x.id)}${isA?`<button class="btn sm" data-a="del" data-id="${p.id}" data-rid="${x.id}">Delete</button>`:''}</div></div>`).join('')}${op[p.id]?(me?`<textarea id="rb${p.id}" style="font:inherit;min-height:60px;margin-top:10px"></textarea><div class="btns" style="margin-top:8px"><button class="btn pri sm" data-a="send" data-id="${p.id}">Send reply</button></div>`:'<p class="note">Log in or create an account above to reply.</p>'):''}</div>`).join(''):'<div class="card"><p class="note">No updates yet.</p></div>'}`};
 const fb=(why)=>{root.innerHTML=`<div class="card"><p class="note neg"><b>Likes, replies and accounts are off:</b> ${why}</p></div>`+((D.updates||[]).length?D.updates.slice().sort((a,b)=>a.d<b.d?1:-1).map(u=>`<div class="card"><small>${fd(u.d)}</small><h3 style="margin:4px 0">${esc(u.t)}</h3><p style="white-space:pre-wrap">${esc(u.b)}</p></div>`).join(''):'<div class="card"><p class="note">No updates yet.</p></div>')};
 const load=async()=>{try{const r=await fetch('api/feed',{headers:H(),cache:'no-store'});if(!r.ok){const tx=await r.text();fb(r.status==404&&tx.includes('KV not configured')?'the KV binding named YQ is missing in Cloudflare (see README step 2).':r.status==404?'api/feed was not found. Put feed.js at functions/api/feed.js in your repo and redeploy.':'the server answered with error '+r.status+'.');return}const j=await r.json();ps=j.posts;me=j.me||'';if(!me){localStorage.removeItem('yq-tok')}draw()}catch(e){fb('this site is not on Cloudflare Pages with live saving, so there is nowhere to store them. Posts from Admin > Home news are shown below read-only.')}};
 root.onclick=async e=>{const t=e.target,a=t.dataset.a;if(!a)return;const id=t.dataset.id,rid=t.dataset.rid;err='';
  if(a=='rp'){op[id]=!op[id];draw();return}
  if(a=='out'){localStorage.removeItem('yq-tok');await load();return}
  let o=null;
  if(a=='in'||a=='up')o={a:a=='in'?'login':'signup',u:$('#au').value,p:$('#ap').value};
  else if(a=='post')o={a:'post',t:$('#pt').value,b:$('#pb').value};
  else if(a=='lk')o={a:'like',id,rid};
  else if(a=='send')o={a:'reply',id,b:$('#rb'+id).value};
  else if(a=='del'){if(!confirm('Delete this?'))return;o={a:'del',id,rid}}
  if(!o)return;const r=await call(o);if(!r.ok)err=r.j.error||'Something went wrong.';else if(r.j.token)localStorage.setItem('yq-tok',r.j.token);else if(a=='send')op[id]=false;await load()};
 load()}
function admin(){const root=$('#adm');
 if(sessionStorage.getItem('yq-auth')!=='1'){root.innerHTML=`<div class="card" style="max-width:380px"><label>Password</label><input id="pw" type="password"><div class="btns" style="margin-top:16px"><button class="btn pri" id="go">Sign in</button></div><p class="note" id="msg"></p></div>`;
  const go=async()=>{const v=$('#pw').value;
   if(API){try{const r=await fetch('api/data',{method:'POST',headers:{'x-admin-password':v}});if(r.ok){sessionStorage.setItem('yq-pw',v);sessionStorage.setItem('yq-auth','1');location.reload()}else $('#msg').textContent='Wrong password.'}catch(e){$('#msg').textContent='Could not reach the server.'}return}
   if(v===D.adminPass){sessionStorage.setItem('yq-auth','1');location.reload()}else $('#msg').textContent='Wrong password.'};$('#go').onclick=go;$('#pw').addEventListener('keydown',e=>{if(e.key=='Enter')go()});return}
 let W=JSON.parse(JSON.stringify(D)),tab=(!D.days.length&&!D.holdings.length)?'setup':'days',all=false,msg=API?'Live saving is on. Changes go straight to your site.':'Changes save in this browser only. See Publish to update the live site.',st=0,dq='',showHelp=false,pvp='index',hist=[];W.ov=W.ov||{};W.updates=W.updates||[];W.faq=W.faq||[];W.orders=W.orders||[];W.trades=W.trades||[];W.bench=W.bench||{name:'',months:[]};
 const tdy=new Date(Date.now()-new Date().getTimezoneOffset()*6e4).toISOString().slice(0,10);
 const tv=()=>sum(W.holdings,h=>h.val),sortD=()=>W.days.sort((a,b)=>a.d<b.d?-1:a.d>b.d?1:0);sortD();
 const save=()=>{W.updated=new Date().toISOString();
  if(!API){localStorage.setItem('yq-data',JSON.stringify(W));msg='Saved in this browser only. Last updated '+fu(W.updated)+'.';return}
  msg='Saving...';clearTimeout(st);st=setTimeout(async()=>{try{const o={...W};delete o.adminPass;const r=await fetch('api/data',{method:'PUT',headers:{'content-type':'application/json','x-admin-password':sessionStorage.getItem('yq-pw')||''},body:JSON.stringify(o)});msg=r.ok?'Saved to the live site. Last updated '+fu(W.updated)+'.':'Could not save ('+r.status+'). Check your password and Cloudflare setup.'}catch(e){msg='Could not save. Check your connection.'}const m=$('#msg');if(m)m.textContent=msg},500)};
 const upsert=(d,p,g,e)=>{W.days=W.days.filter(x=>x.d!=d);W.days.push(Object.assign({d,p,g},e||{}));sortD()};

 const applyTrade=t=>{const cashRe=/cash/i;let h=W.holdings.find(x=>String(x.t).toUpperCase()==t.t&&!cashRe.test(x.c));const cash=W.holdings.find(x=>cashRe.test(x.c)),amt=t.sh*t.px;
  if(t.side=='BUY'){if(!h){h={n:t.t,t:t.t,c:'Equity',date:t.d,shares:0,inv:0,val:0};W.holdings.push(h)}h.shares=(+h.shares||0)+t.sh;h.inv=(+h.inv||0)+amt;h.val=(+h.val||0)+amt;if(cash){cash.inv=Math.max(0,cash.inv-amt);cash.val=Math.max(0,cash.val-amt)}}
  else{if(!h||!+h.shares)return 'You do not hold any '+t.t+' to sell.';const n=Math.min(t.sh,h.shares),f=n/h.shares,cs=h.inv*f,pr=n*t.px;h.sc=(+h.sc||0)+cs;h.proc=(+h.proc||0)+pr;h.sold=t.d;h.inv-=cs;h.val-=h.val*f;h.shares-=n;if(h.shares<1e-9){h.shares=0;h.inv=0;h.val=0}if(cash){cash.inv+=cs;cash.val+=pr}else W.holdings.push({n:'Cash reserve',t:'USD',c:'Cash',date:t.d,shares:0,inv:cs,val:pr});t.pl=pr-cs}
  return ''};
 const hTable=()=>`<div class="head"><h3>Holdings</h3><button class="btn sm pri" data-a="addH">Add holding</button></div><div class="tw"><table><tr><th>Name</th><th>Ticker</th><th>Class</th><th>First invested</th><th>Shares</th><th>Invested ($)</th><th>Current value ($)</th><th>Last sold</th><th>Cost sold ($)</th><th>Sale proceeds ($)</th><th></th></tr>${W.holdings.map((h,i)=>`<tr><td>${inp('hold',i,'n',h.n)}</td><td>${inp('hold',i,'t',h.t)}</td><td>${inp('hold',i,'c',h.c)}</td><td>${inp('hold',i,'date',h.date||'','date')}</td><td>${inp('hold',i,'shares',h.shares||0,'number')}</td><td>${inp('hold',i,'inv',h.inv,'number')}</td><td>${inp('hold',i,'val',h.val,'number')}</td><td>${inp('hold',i,'sold',h.sold||'','date')}</td><td>${inp('hold',i,'sc',h.sc||0,'number')}</td><td>${inp('hold',i,'proc',h.proc||0,'number')}</td><td><button class="btn sm" data-a="delH" data-i="${i}">Remove</button></td></tr>`).join('')}</table></div><p class="note" id="tot">Total invested ${$m(sum(W.holdings,h=>h.inv))}. Current value ${$m(tv())}. Selling via Orders and trades fills the sold columns for you; a holding with proceeds and 0 shares shows as a sold position.</p>`;
 const siteCard=()=>`<div class="card"><h3>Site details</h3><div class="row3"><div><label>Firm name</label>${inp('set',0,'firm',W.firm||'')}</div><div><label>Start date</label>${inp('set',0,'start',W.start||'','date')}</div><div><label>Number of investors</label>${inp('set',0,'investors',W.investors)}</div></div><label>Home headline</label>${inp('set',0,'headline',W.headline||'')}<label>Home subheading</label>${inp('set',0,'sub',W.sub||'')}<div class="row3"><div><label>Contact email</label>${inp('set',0,'contactEmail',W.contactEmail||'')}</div><div><label>Phone</label>${inp('set',0,'phone',W.phone||'')}</div><div><label>Minimum investment</label>${inp('set',0,'minInvest',W.minInvest||'')}</div>${API?'':`<div><label>Admin password</label>${inp('set',0,'adminPass',W.adminPass)}</div>`}</div><label>Form endpoint (optional)</label>${inp('set',0,'formEndpoint',W.formEndpoint||'')}<p class="note">With no endpoint the Invest form opens the visitor's email app. For direct enquiries, make a free Formspree form and paste its URL.</p></div>`;
 const nxt=()=>{const l=W.days.length?W.days[W.days.length-1].d:'';if(!l)return tdy;const o=new Date(l+'T00:00:00');do{o.setDate(o.getDate()+1)}while(o.getDay()%6==0);const r=o.getFullYear()+'-'+String(o.getMonth()+1).padStart(2,'0')+'-'+String(o.getDate()).padStart(2,'0');return r>tdy?tdy:r};
 const inp=(s,i,f,v,t='text')=>`<input data-s="${s}" data-i="${i}" data-f="${f}" type="${t}" ${t=='number'?'step="any"':''} value="${String(v).replace(/"/g,'&quot;')}">`;
 const sel=(s,i,f,v,o)=>`<select data-s="${s}" data-i="${i}" data-f="${f}">${o.map(x=>`<option${x==v?' selected':''}>${x}</option>`).join('')}</select>`;
 const tin=(s,i,f,v)=>`<textarea data-s="${s}" data-i="${i}" data-f="${f}">${esc(v)}</textarea>`;
 const tabs=[['setup','Setup'],['front','Front page'],['days','Daily returns'],['hold','Holdings'],['trades','Orders and trades'],['upd','Home news'],['faq','FAQ'],['bench','Benchmark'],['site','Site details'],['view','Preview'],['pub','Publish']]
 const HELP={setup:[['Checklist','Shows what is still missing before the site is ready.'],['Start fresh','Deletes sample data, all at once or one part. Undo (top) brings it back.'],['Site details','Firm name, start date, investors, headline, contact info and password.'],['Holdings','What you own: shares, amount invested, current value.']],front:[['Front page numbers','Replace any automatic number on Home and Portfolio with your own. Empty box = automatic.'],['Clear all overrides','Goes back to fully automatic numbers.']],days:[['Add a day','Enter a whole return % or a closing value. The other is worked out.'],['± button','Flips a number between gain and loss.'],['Per holding','Optional return for each holding. Leave the whole return empty to work it out from these.'],['Update holding values','Moves your holding values by the day return so totals and charts stay current.'],['CSV upload','Add many days at once from a spreadsheet. Skipped lines are listed.'],['Delete range','Removes all days between two dates.']],hold:[['Holdings table','Edit shares, invested and value directly. Sold columns fill in automatically when you record a sale.'],['Set total value','Type your real total and the non-cash holdings are scaled to match.']],trades:[['Orders','Pending buys and sells. Fill moves one into trade history.'],['Record a trade','For a SELL the site works out profit or loss on those shares from what you paid, and shows it in Trades and Portfolio.'],['Update holdings and cash','On: shares, cost and cash change automatically. Off: it only logs the trade.']],upd:[['Home news','Short news items shown on the home page (latest 3). The public Updates feed is separate: sign in here first, then open the Updates page from the site menu to post, and use Delete there to remove posts or replies.']],faq:[['FAQ','Questions and answers shown on the Invest page.']],bench:[['Benchmark','Monthly returns of an index you compare against. Shown on the Profits page.']],site:[['Site details','Same fields as in Setup.']],view:[['Live preview','See the real pages inside the admin to check your changes.']],pub:[['Download data.js','Backup, and how to publish if live saving is off.'],['Restore','Load a data.js you downloaded before.']]};;
 const draw=()=>{let c='';
  if(tab=='days'){const dd=W.days.map((x,i)=>({x,i})).sort((a,b)=>a.x.d<b.x.d?1:a.x.d>b.x.d?-1:0),sh=(dq?dd.filter(r=>r.x.d.includes(dq)):dd).slice(0,all||dq?99999:15);
   c=`<div class="card"><h3>Add a day's return</h3><div class="row4"><div><label>Date</label><input id="nd" type="date" value="${nxt()}"></div><div><label>Whole return (%)</label><div style="display:flex;gap:6px"><input id="np" type="number" step="any" placeholder="0.25"><button class="btn sm" type="button" data-a="neg" title="Flip + / -">±</button></div></div><div><label>or Closing value ($)</label><input id="nv" type="number" step="any" placeholder="total portfolio value"></div><div><label>Gain ($), optional</label><div style="display:flex;gap:6px"><input id="ng" type="number" step="any" placeholder="auto"><button class="btn sm" type="button" data-a="neg" title="Flip + / -">±</button></div></div></div><details><summary>Return per holding (optional)</summary><p class="note">Fill in any holdings that moved. Leave the whole return blank to have it worked out from these.</p>${W.holdings.map((h,i)=>/cash/i.test(h.c)||!+h.shares&&!+h.val?'':`<div class="row3" style="align-items:end;margin-top:6px"><div>${esc(h.n)} <small>${esc(h.t)}</small></div><div style="display:flex;gap:6px"><input id="hr${i}" type="number" step="any" placeholder="%"><button class="btn sm" type="button" data-a="neg" title="Flip + / -">±</button></div></div>`).join('')}</details><label>Note (optional, shown on the Daily page)</label><input id="nn"><label style="display:flex;gap:8px;align-items:center"><input id="na" type="checkbox" checked style="width:auto"> Also update holding values (non-cash) to match</label><div class="btns" style="margin-top:12px"><button class="btn pri" data-a="addDay">Add day</button></div><p class="note">The ± buttons flip a number between gain and loss. Adding an existing date replaces it (holding values are not changed again). Months and totals update automatically.</p></div>
<div class="card"><h3>Upload returns (CSV)</h3><p class="note">Columns: date, return %, gain $ (optional). With a header row, columns are found by name (date, return/%, gain/profit, value/balance). If there is no return column but there is a value column, returns are worked out from one row to the next (first row = baseline). Comma, semicolon or tab separated. Lines that cannot be read are skipped and listed.</p><input id="file" type="file" accept=".csv,.txt"><label>Dates like 03/04/2026 are</label><select id="dfm"><option value="md">Month/Day/Year</option><option value="dm">Day/Month/Year</option></select><label>Or paste rows</label><textarea id="csv" placeholder="date,return_pct,gain_usd&#10;2026-10-08,0.21,10200"></textarea><div class="btns" style="margin-top:12px"><button class="btn pri" data-a="csv">Import rows</button></div></div>
<div class="card"><div class="head"><h3>Logged days (${W.days.length})</h3><div class="btns"><input id="dq" placeholder="Search e.g. 2026-09" value="${esc(dq)}" style="width:180px"><button class="btn sm" data-a="delSel">Delete ticked</button><button class="btn sm" data-a="more">${all?'Show recent':'Show all'}</button></div></div><p class="note">Tick days (or the top box to tick every day shown, use Show all first for everything) and press Delete ticked. Use Undo to bring them back.</p><div class="tw"><table><tr><th><input type="checkbox" id="ckall" style="width:auto;min-width:0" title="Select all shown"></th><th>Date</th><th>Return %</th><th>Gain $</th><th>Note</th><th></th></tr>${sh.map(({x,i})=>`<tr><td><input type="checkbox" class="ck" data-k="${i}" style="width:auto;min-width:0"></td><td>${inp('days',i,'d',x.d,'date')}</td><td>${inp('days',i,'p',x.p,'number')}</td><td>${inp('days',i,'g',x.g,'number')}</td><td>${inp('days',i,'n',x.n||'')}</td><td><button class="btn sm" data-a="delDay" data-i="${i}">Delete</button></td></tr>`).join('')}</table></div><div class="row4" style="margin-top:14px"><div><label>Delete days from</label><input id="rf" type="date"></div><div><label>to</label><input id="rt" type="date"></div><div><button class="btn sm" data-a="rangeDel">Delete range</button></div></div></div>`}
  if(tab=='hold')c=`<div class="card">${hTable()}</div>`;
  if(tab=='setup'){const ck=(o,t)=>`<li>${o?'✓':'○'} ${t}</li>`;c=`<div class="card"><h3>Setup checklist</h3><ul class="steps" style="list-style:none;padding:0">${ck(W.start,'Start date set')}${ck(W.holdings.length,'Holdings entered ('+W.holdings.length+')')}${ck(W.days.length,'Daily returns logged ('+W.days.length+')')}${ck(W.contactEmail&&!/yourdomain/.test(W.contactEmail),'Contact email set')}</ul></div><div class="card"><h3>Start fresh</h3><p class="note">Delete everything at once, or just one part. Firm name, site text, contact details and password stay. Use Undo at the top if you slip.</p><div class="btns"><button class="btn" data-a="wipe">Delete all data</button><button class="btn sm" data-a="wipeDays">Only daily returns</button><button class="btn sm" data-a="wipeHold">Only holdings</button><button class="btn sm" data-a="wipeTrd">Only orders and trades</button></div></div>${siteCard()}<div class="card">${hTable()}</div><p class="note">Then use Daily returns each day, and Orders and trades for buys and sells.</p>`}
  if(tab=='site')c=siteCard();
  if(tab=='pub')c=`<div class="card"><h3>Publish to the live site</h3><p class="note">${API?'Live saving is on. Every change is saved to your site and visitors see it right away. Download data.js to keep a backup.':'Changes save automatically, but only in this browser. To update the live site for everyone: download data.js, replace <b>assets/data.js</b> in your repo, and push. Or set up live saving on Cloudflare (see README).'}</p><div class="btns"><button class="btn pri" data-a="dl">Download data.js</button><button class="btn" data-a="reset">Discard local changes</button><button class="btn" data-a="out">Sign out</button></div><label>Restore from a downloaded data.js</label><input id="imp" type="file" accept=".js,.json"></div>`;
  if(tab=='trades'){const so=W.orders.map((o,i)=>({o,i})).reverse(),st2=W.trades.map((x,i)=>({x,i})).reverse(),SD=['BUY','SELL'];
   c=`<div class="card"><h3>New order</h3><div class="row4"><div><label>Date</label><input id="od" type="date" value="${tdy}"></div><div><label>Ticker</label><input id="ot" placeholder="AAPL"></div><div><label>Side</label><select id="os"><option>BUY</option><option>SELL</option></select></div><div><label>Type</label><select id="oy"><option>Limit</option><option>Market</option><option>Stop</option></select></div><div><label>Shares</label><input id="on" type="number" step="any"></div><div><label>Price ($, blank for market)</label><input id="op" type="number" step="any"></div><div><button class="btn pri" data-a="addOrd">Place order</button></div></div></div>
<div class="card"><h3>Orders (${W.orders.length})</h3><div class="tw"><table><tr><th>Date</th><th>Ticker</th><th>Side</th><th>Type</th><th>Shares</th><th>Price</th><th>Status</th><th></th></tr>${so.map(({o,i})=>`<tr><td>${inp('ord',i,'d',o.d,'date')}</td><td>${inp('ord',i,'t',o.t)}</td><td>${sel('ord',i,'side',o.side,SD)}</td><td>${sel('ord',i,'type',o.type,['Limit','Market','Stop'])}</td><td>${inp('ord',i,'sh',o.sh,'number')}</td><td>${inp('ord',i,'px',o.px,'number')}</td><td>${sel('ord',i,'status',o.status,['Open','Filled','Cancelled'])}</td><td><button class="btn sm" data-a="fillOrd" data-i="${i}">Fill</button> <button class="btn sm" data-a="delOrd" data-i="${i}">Delete</button></td></tr>`).join('')}</table></div><p class="note">Fill moves the order into trade history at its price. Update the holding's shares and amounts in the Holdings tab separately.</p></div>
<div class="card"><h3>Record a trade</h3><div class="row4"><div><label>Date</label><input id="td" type="date" value="${tdy}"></div><div><label>Ticker</label><input id="tt"></div><div><label>Side</label><select id="ts"><option>BUY</option><option>SELL</option></select></div><div><label>Shares</label><input id="tn" type="number" step="any"></div><div><label>Price ($)</label><input id="tp" type="number" step="any"></div><div><label>Note</label><input id="tm"></div><div><label style="display:flex;gap:8px;align-items:center"><input id="tu" type="checkbox" checked style="width:auto"> Update holdings and cash</label></div><div><button class="btn pri" data-a="addTrd">Add trade</button></div></div></div>
<div class="card"><h3>Trade history (${W.trades.length})</h3><div class="tw"><table><tr><th>Date</th><th>Ticker</th><th>Side</th><th>Shares</th><th>Price</th><th>Note</th><th></th></tr>${st2.map(({x,i})=>`<tr><td>${inp('trd',i,'d',x.d,'date')}</td><td>${inp('trd',i,'t',x.t)}</td><td>${sel('trd',i,'side',x.side,SD)}</td><td>${inp('trd',i,'sh',x.sh,'number')}</td><td>${inp('trd',i,'px',x.px,'number')}</td><td>${inp('trd',i,'note',x.note||'')}</td><td><button class="btn sm" data-a="delTrd" data-i="${i}">Delete</button></td></tr>`).join('')}</table></div></div>`}
  if(tab=='upd')c=`<div class="card"><h3>Post an update</h3><div class="row3"><div><label>Date</label><input id="ud" type="date" value="${tdy}"></div><div style="grid-column:span 2"><label>Title</label><input id="ut"></div></div><label>Text</label><textarea id="ub" style="min-height:70px"></textarea><div class="btns" style="margin-top:12px"><button class="btn pri" data-a="addUpd">Post update</button></div><p class="note">The latest three show on the home page.</p></div><div class="card"><h3>Posted updates</h3><div class="tw"><table><tr><th>Date</th><th>Title</th><th>Text</th><th></th></tr>${W.updates.map((u,i)=>`<tr><td>${inp('upd',i,'d',u.d,'date')}</td><td>${inp('upd',i,'t',u.t)}</td><td>${tin('upd',i,'b',u.b)}</td><td><button class="btn sm" data-a="delUpd" data-i="${i}">Delete</button></td></tr>`).join('')}</table></div></div>`;
  if(tab=='faq')c=`<div class="card"><h3>Add a question</h3><label>Question</label><input id="fq"><label>Answer</label><textarea id="fa" style="min-height:70px"></textarea><div class="btns" style="margin-top:12px"><button class="btn pri" data-a="addFaq">Add question</button></div><p class="note">Shown on the Invest page.</p></div><div class="card"><h3>Questions</h3><div class="tw"><table><tr><th>Question</th><th>Answer</th><th></th></tr>${W.faq.map((f,i)=>`<tr><td>${inp('faq',i,'q',f.q)}</td><td>${tin('faq',i,'a',f.a)}</td><td><button class="btn sm" data-a="delFaq" data-i="${i}">Delete</button></td></tr>`).join('')}</table></div></div>`;
  if(tab=='bench')c=`<div class="card"><h3>Benchmark</h3><label>Benchmark name</label><input data-s="bn" data-i="0" data-f="n" value="${esc(W.bench.name)}"><div class="row4"><div><label>Month</label><input id="bk" type="month" value="${tdy.slice(0,7)}"></div><div><label>Return (%)</label><input id="bpp" type="number" step="any"></div><div><button class="btn pri" data-a="addBm">Add month</button></div></div><p class="note">Enter the monthly returns of an index or fund to compare against. The Profits page shows both side by side.</p></div><div class="card"><h3>Benchmark months</h3><div class="tw"><table><tr><th>Month</th><th>Return %</th><th></th></tr>${W.bench.months.map((m,i)=>`<tr><td>${inp('bm',i,'k',m.k,'month')}</td><td>${inp('bm',i,'p',m.p,'number')}</td><td><button class="btn sm" data-a="delBm" data-i="${i}">Delete</button></td></tr>`).join('')}</table></div></div>`;
  root.innerHTML=`<div class="tabs">${tabs.map(t=>`<button class="btn sm ${tab==t[0]?'pri':''}" data-a="tab" data-t="${t[0]}">${t[1]}</button>`).join('')}<button class="btn sm" data-a="undo">↶ Undo</button><button class="btn sm" data-a="help">? Help</button><a class="btn sm" href="index.html" target="_blank">View site</a><small class="note" style="margin-left:8px">v6</small></div>${showHelp?`<div class="card"><h3>What this tab does</h3>${(HELP[tab]||[]).map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div>`:''}<p class="note" id="msg">${msg}</p>${c}`};
 root.onchange=e=>{const t=e.target;
  if(t.id=='imp'&&t.files[0]){const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result.replace(/^[\s\S]*?window\.YQ_DEFAULT\s*=\s*/,'').replace(/;\s*$/,''));W={...W,...o};W.updates=W.updates||[];W.faq=W.faq||[];W.orders=W.orders||[];W.trades=W.trades||[];W.bench=W.bench||{name:'',months:[]};save();msg='Imported.'}catch(x){msg='That file could not be read.'}draw()};r.readAsText(t.files[0]);return}
  if(t.id=='file'&&t.files[0]){const r=new FileReader();r.onload=()=>{$('#csv').value=r.result};r.readAsText(t.files[0]);return}
  if(t.id=='ckall'){document.querySelectorAll('.ck').forEach(c=>c.checked=t.checked);return}if(t.id=='dq'){dq=t.value;draw();return}const{s,i,f}=t.dataset;if(!s)return;hist.push(JSON.stringify(W));if(hist.length>30)hist.shift();
  if(s=='set'){W[f]=t.value;if(f=='start'&&t.value)W.since=new Date(t.value+'T00:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'})}
  else if({upd:1,faq:1,ord:1,trd:1}[s]){W[{upd:'updates',faq:'faq',ord:'orders',trd:'trades'}[s]][i][f]=(f=='sh'||f=='px')?num(t.value):t.value}
  else if(s=='ov')W.ov[f]=t.value;
  else if(s=='bn')W.bench.name=t.value;
  else if(s=='bm')W.bench.months[i][f]=f=='p'?num(t.value):t.value;
  else if(s=='hold')W.holdings[i][f]=['inv','val','shares','sc','proc'].includes(f)?num(t.value):t.value;
  else{const x=W.days[i];if(f=='d')x.d=t.value;else if(f=='p'){x.p=num(t.value);x.g=Math.round(x.p/100*tv());const g=t.closest('tr').querySelector('[data-f=g]');if(g)g.value=x.g}else if(f=='n')x.n=t.value;else x.g=num(t.value)}
  save();$('#msg').textContent=msg;const n=$('#tot');if(n)n.textContent=`Total invested ${$m(sum(W.holdings,h=>h.inv))}. Current value ${$m(tv())}. Weights, gains and the allocation chart update automatically.`};
 root.onclick=e=>{const a=e.target.dataset.a;if(!a)return;const i=+e.target.dataset.i;
  if(a=='neg'){const n=e.target.previousElementSibling;if(n&&n.value!=='')n.value=String(-parseFloat(n.value));return}
  if(a=='help'){showHelp=!showHelp;draw();return}
  if(a=='pvp'){pvp=e.target.dataset.t;draw();return}
  if(a=='undo'){if(hist.length){W=JSON.parse(hist.pop());save();msg='Undid the last change.'}else msg='Nothing to undo.';draw();return}
  if(!['tab','out','dl','more','reset','help','pvp'].includes(a)){hist.push(JSON.stringify(W));if(hist.length>30)hist.shift()}
  if(a=='tab'){tab=e.target.dataset.t;draw();return}
  if(a=='out'){sessionStorage.removeItem('yq-auth');sessionStorage.removeItem('yq-pw');location.reload();return}
  if(a=='reset'){localStorage.removeItem('yq-data');location.reload();return}
  if(a=='dl'){sortD();const l=document.createElement('a');l.href=URL.createObjectURL(new Blob(['window.YQ_DEFAULT = '+JSON.stringify(W,null,1)+';\n']));l.download='data.js';l.click();return}
  if(a=='addDay'){const d=$('#nd').value,cv=$('#nv').value,pv=$('#np').value,t0=tv(),hr={};W.holdings.forEach((h,i)=>{const v=$('#hr'+i);if(v&&v.value!==''&&!isNaN(parseFloat(v.value)))hr[h.t||h.n]=[i,num(v.value)]});const hn=Object.keys(hr).length;if(!d||(pv===''&&cv===''&&!hn)){msg='Enter a date and a return %, a closing value, or per-holding returns.';draw();return}const ex=W.days.some(x=>x.d==d);
   let g=hn?Math.round(sum(Object.values(hr),r=>W.holdings[r[0]].val*r[1]/100)):0,p;if(pv!=='')p=num(pv);else if(cv!=='')p=t0?(num(cv)/t0-1)*100:0;else p=t0?g/t0*100:0;p=Math.round(p*100)/100;
   if($('#ng').value!=='')g=num($('#ng').value);else if(pv===''&&cv!=='')g=Math.round(num(cv)-t0);else if(pv!==''||!hn)g=Math.round(p/100*t0);
   const x2={};if(hn){x2.h={};Object.keys(hr).forEach(k=>x2.h[k]=hr[k][1])}if($('#nn').value.trim())x2.n=$('#nn').value.trim();
   if($('#na').checked&&!ex&&t0){if(hn)Object.values(hr).forEach(r=>{const h=W.holdings[r[0]];h.val=Math.round(h.val*(1+r[1]/100))});else{const cash=sum(W.holdings.filter(h=>/cash/i.test(h.c)),h=>h.val),k=(t0+g-cash)/(t0-cash);if(isFinite(k)&&k>0)W.holdings.forEach(h=>{if(!/cash/i.test(h.c))h.val=Math.round(h.val*k)})}}
   upsert(d,p,g,x2)}
  else if(a=='csv'){const fmt=$('#dfm').value,rows=$('#csv').value.split(/\r?\n/).filter(l=>l.trim()),dl=/\t/.test(rows[0]||'')?'\t':/;/.test(rows[0]||'')?';':',',cl=s=>(s||'').trim().replace(/^"|"$/g,'').trim();
   const pd=s=>{s=cl(s);let m=s.match(/^(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})$/),y,mo,dd;if(m){y=m[1];mo=m[2];dd=m[3]}else if(m=s.match(/^(\d{1,2})[-\/.](\d{1,2})[-\/.](\d{4})$/)){y=m[3];[mo,dd]=fmt=='dm'?[m[2],m[1]]:[m[1],m[2]]}else{const t=Date.parse(s);if(isNaN(t)||!/[a-z]/i.test(s))return'';const o=new Date(t);return o.getFullYear()+'-'+String(o.getMonth()+1).padStart(2,'0')+'-'+String(o.getDate()).padStart(2,'0')}
    const iso=`${y}-${String(mo).padStart(2,'0')}-${String(dd).padStart(2,'0')}`,c=new Date(iso+'T00:00:00');return c.getMonth()+1==+mo&&c.getDate()==+dd?iso:''};
   const ci={d:0,p:1,g:2,v:-1},sk=[];let n=0,base=null,st=0;const h0=rows[0]?rows[0].split(dl).map(x=>cl(x).toLowerCase()):[];
   if(h0.length&&!pd(h0[0])){h0.forEach((x,k)=>{if(/date|day/.test(x))ci.d=k;else if(/value|balance|nav|close/.test(x))ci.v=k;else if(/gain|profit|\$|usd|pnl/.test(x))ci.g=k;else if(/ret|%|pct|percent/.test(x))ci.p=k});if(!h0.some(x=>/ret|%|pct|percent/.test(x)))ci.p=-1;if(!h0.some(x=>/gain|profit|\$|usd|pnl/.test(x)))ci.g=-1;st=1}
   rows.slice(st).forEach((l,k)=>{const q=l.split(dl),d=pd(q[ci.d]),ln=k+st+1;if(!d){sk.push(ln);return}let p=ci.p>=0&&cl(q[ci.p])!==''?num(q[ci.p]):null,g=ci.g>=0&&cl(q[ci.g])!==''?num(q[ci.g]):null;
    if(p===null&&ci.v>=0){const v=num(q[ci.v]);if(base===null){base=v;sk.push(ln+' (baseline)');return}p=(v/base-1)*100;if(g===null)g=Math.round(v-base);base=v}
    if(p===null){sk.push(ln);return}p=Math.round(p*100)/100;upsert(d,p,g===null?Math.round(p/100*tv()):g);n++});
   save();msg=`Imported ${n} rows.`+(sk.length?` Skipped line(s): ${sk.slice(0,15).join(', ')}.`:'');draw();return}
  else if(a=='addUpd'){const d=$('#ud').value,t=$('#ut').value.trim();if(!d||!t){msg='Enter a date and a title.';draw();return}W.updates.push({d,t,b:$('#ub').value})}
  else if(a=='delUpd')W.updates.splice(i,1);
  else if(a=='addFaq'){const q=$('#fq').value.trim();if(!q){msg='Enter a question.';draw();return}W.faq.push({q,a:$('#fa').value})}
  else if(a=='delFaq')W.faq.splice(i,1);
  else if(a=='addBm'){const k=$('#bk').value;if(!k||$('#bpp').value===''){msg='Enter a month and a return.';draw();return}W.bench.months=W.bench.months.filter(x=>x.k!=k);W.bench.months.push({k,p:num($('#bpp').value)});W.bench.months.sort((a,b)=>a.k<b.k?-1:1)}
  else if(a=='delBm')W.bench.months.splice(i,1);
  else if(a=='addOrd'){const t=$('#ot').value.trim().toUpperCase(),n=num($('#on').value);if(!t||!n){msg='Enter a ticker and number of shares.';draw();return}W.orders.push({d:$('#od').value||tdy,t,side:$('#os').value,type:$('#oy').value,sh:n,px:num($('#op').value),status:'Open'})}
  else if(a=='fillOrd'){const o=W.orders[i];if(o){W.trades.push({d:tdy,t:o.t,side:o.side,sh:o.sh,px:o.px,note:'Filled '+o.type+' order'});W.orders.splice(i,1)}}
  else if(a=='delOrd')W.orders.splice(i,1);
  else if(a=='addTrd'){const t=$('#tt').value.trim().toUpperCase(),n=num($('#tn').value);if(!t||!n){msg='Enter a ticker and number of shares.';draw();return}const tr={d:$('#td').value||tdy,t,side:$('#ts').value,sh:n,px:num($('#tp').value),note:$('#tm').value};if($('#tu').checked){const er=applyTrade(tr);if(er){msg=er;draw();return}}W.trades.push(tr)}
  else if(a=='wipe'){if(!confirm('Delete ALL data (returns, holdings, orders, trades, updates, FAQ, benchmark)? This cannot be undone unless you have a backup.'))return;Object.assign(W,{days:[],holdings:[],orders:[],trades:[],updates:[],faq:[],bench:{name:'Benchmark',months:[]},investors:'0',start:'',since:'',ov:{}});sortD()}
  else if(a=='clrOv')W.ov={};
  else if(a=='scaleTo'){const T=num($('#stv').value),t0=tv(),cash=sum(W.holdings.filter(h=>/cash/i.test(h.c)),h=>h.val),k=(T-cash)/(t0-cash);if(!T||!isFinite(k)||k<=0){msg='Enter a total (it must be more than your cash).';draw();return}W.holdings.forEach(h=>{if(!/cash/i.test(h.c))h.val=Math.round(h.val*k)})}
  else if(a=='delSel'){const k=new Set([...document.querySelectorAll('.ck:checked')].map(c=>+c.dataset.k));if(!k.size){msg='Tick the days you want to delete first.';draw();return}if(!confirm('Delete '+k.size+' day(s)?'))return;W.days=W.days.filter((x,i)=>!k.has(i))}
  else if(a=='wipeDays'){if(!confirm('Delete ALL daily returns?'))return;W.days=[]}
  else if(a=='wipeHold'){if(!confirm('Delete ALL holdings?'))return;W.holdings=[]}
  else if(a=='wipeTrd'){if(!confirm('Delete ALL orders and trades?'))return;W.orders=[];W.trades=[]}
  else if(a=='rangeDel'){const f=$('#rf').value,t=$('#rt').value;if(!f||!t){msg='Pick a from and to date.';draw();return}const b=W.days.length;W.days=W.days.filter(x=>x.d<f||x.d>t);save();msg='Deleted '+(b-W.days.length)+' days.';draw();return}
  else if(a=='delTrd')W.trades.splice(i,1);
  else if(a=='addH')W.holdings.push({n:'New holding',t:'',c:'Equity',date:tdy,shares:0,inv:0,val:0});
  else if(a=='delH')W.holdings.splice(i,1);
  else if(a=='delDay')W.days.splice(i,1);
  else if(a=='more')all=!all;
  save();draw()};
 draw()}
if(pg==='admin')admin();
if(pg==='updates')feed();

})();
